[loggers]
keys=root,sage

[handlers]
keys=console

[formatters]
keys=default

[logger_root]
level=WARNING
handlers=console

[logger_sage]
level=DEBUG
handlers=console
qualname=sage
propagate=0

[handler_console]
class=logging.StreamHandler
formatter=default
level=DEBUG

[formatter_default]
class=apollo_logging.formatter.ColorFormatter
format='$YELLOW%(asctime)s$RESET|$MAGENTA%(module)s.%(funcName)s:L%(lineno)s$RESET|$COLOR%(levelname)s$RESET %(message)s'
