import type { KeyBinding } from "../types/shortcuts.js";

export const defaultKeybindings: KeyBinding[] = [
  {
    key: "upArrow",
    ctrl: true,
    modes: ["normal", "command"],
    action: "scroll-up",
    description: "Scroll up",
    category: "navigation",
  },
  {
    key: "downArrow",
    ctrl: true,
    modes: ["normal", "command"],
    action: "scroll-down",
    description: "Scroll down",
    category: "navigation",
  },
  {
    key: "pageUp",
    modes: ["normal", "command"],
    action: "page-up",
    description: "Page up",
    category: "navigation",
  },
  {
    key: "pageDown",
    modes: ["normal", "command"],
    action: "page-down",
    description: "Page down",
    category: "navigation",
  },
  {
    key: "home",
    modes: ["normal", "command"],
    action: "scroll-top",
    description: "Scroll to top",
    category: "navigation",
  },
  {
    key: "end",
    modes: ["normal", "command"],
    action: "scroll-bottom",
    description: "Scroll to bottom",
    category: "navigation",
  },

  {
    key: "n",
    ctrl: true,
    modes: ["normal", "command"],
    action: "new-session",
    description: "New session",
    category: "session",
  },
  {
    key: "n",
    ctrl: true,
    shift: true,
    modes: ["normal", "command"],
    action: "session-picker",
    description: "Open session picker",
    category: "session",
  },
  {
    key: "s",
    ctrl: true,
    modes: ["normal", "command"],
    action: "save-session",
    description: "Save current session",
    category: "session",
  },

  {
    key: "b",
    ctrl: true,
    modes: ["normal", "command"],
    action: "toggle-sidebar",
    description: "Toggle sidebar",
    category: "view",
  },
  {
    key: "l",
    ctrl: true,
    modes: ["normal", "command"],
    action: "clear-output",
    description: "Clear output",
    category: "view",
  },
  {
    key: "\\",
    ctrl: true,
    modes: ["normal", "command"],
    action: "toggle-split",
    description: "Toggle split view",
    category: "view",
  },
  {
    key: "1",
    ctrl: true,
    modes: ["normal", "command"],
    action: "sidebar-tab-1",
    description: "Sidebar tab 1",
    category: "view",
  },
  {
    key: "2",
    ctrl: true,
    modes: ["normal", "command"],
    action: "sidebar-tab-2",
    description: "Sidebar tab 2",
    category: "view",
  },
  {
    key: "3",
    ctrl: true,
    modes: ["normal", "command"],
    action: "sidebar-tab-3",
    description: "Sidebar tab 3",
    category: "view",
  },
  {
    key: "4",
    ctrl: true,
    modes: ["normal", "command"],
    action: "sidebar-tab-4",
    description: "Sidebar tab 4",
    category: "view",
  },

  {
    key: "return",
    modes: ["insert", "normal"],
    action: "send",
    description: "Send message",
    category: "input",
  },
  {
    key: "return",
    shift: true,
    modes: ["insert"],
    action: "newline",
    description: "Insert newline",
    category: "input",
  },
  {
    key: "c",
    ctrl: true,
    modes: ["normal", "insert", "command", "leader"],
    action: "cancel",
    description: "Cancel / quit",
    category: "input",
  },
  {
    key: "z",
    ctrl: true,
    modes: ["insert"],
    action: "undo",
    description: "Undo",
    category: "input",
  },
  {
    key: "upArrow",
    modes: ["insert", "normal"],
    action: "history-prev",
    description: "Previous history entry",
    category: "input",
  },
  {
    key: "downArrow",
    modes: ["insert", "normal"],
    action: "history-next",
    description: "Next history entry",
    category: "input",
  },

  {
    key: "p",
    ctrl: true,
    modes: ["normal", "command"],
    action: "permission-approve",
    description: "Approve pending permission",
    category: "agent",
  },
  {
    key: "k",
    ctrl: true,
    modes: ["normal", "command"],
    action: "command-palette",
    description: "Open command palette",
    category: "agent",
  },
  {
    key: "t",
    ctrl: true,
    modes: ["normal", "command"],
    action: "tool-list",
    description: "Show tool list",
    category: "agent",
  },
  {
    key: "d",
    ctrl: true,
    modes: ["normal", "command"],
    action: "dismiss",
    description: "Dismiss notification",
    category: "agent",
  },

  {
    key: "?",
    modes: ["leader"],
    action: "help",
    description: "Show keyboard help",
    category: "leader",
  },
  {
    key: "S",
    modes: ["leader"],
    action: "save-session",
    description: "Save session (leader)",
    category: "leader",
  },
  {
    key: "K",
    modes: ["leader"],
    action: "kill-bg",
    description: "Kill background tasks",
    category: "leader",
  },
  {
    key: "R",
    modes: ["leader"],
    action: "restart-backend",
    description: "Restart backend",
    category: "leader",
  },
  {
    key: "E",
    modes: ["leader"],
    action: "export-session",
    description: "Export session",
    category: "leader",
  },
  {
    key: "Q",
    modes: ["leader"],
    action: "quit-all",
    description: "Quit all",
    category: "leader",
  },
];
